### ISSUE TITLE
Function to add parts' ports in a SysML IBD

### ISSUE THREAD

**Issue by guillaumefinance** [Helmut-Ortmann/EnterpriseArchitect_hoTools#1]
Working on a SysML IBD, I run Sparx Synchronize Structural Elements to get all parts.
When the type of a part i.e. a Block has port, I need to select each part, open Structural Elements and add inherited Ports **to be created** under the part.
Would it be possible to have a function to add & display all ports on the displayed parts on an IBD (this feature may apply to other diagrams, not SysML only.)

**Comment by Helmut-Ortmann** [comment]
Thanks for the valuable explanation. I can reproduce the issue, and I'll take of it. Probably this or next week.

**Comment by Helmut-Ortmann** [comment]
Fixed. hoTools synchronizes Part Ports from Class/Block Ports. EA maintains the relationship in PDATA3.
[See Port Synchronization:](https://github.com/Helmut-Ortmann/EnterpriseArchitect_hoTools/wiki/PortSynchronization)
