### ISSUE TITLE
Add an EA-16 x64 release build, or installer build for both x86 and x64?

### ISSUE THREAD

**Issue by timoc** [Helmut-Ortmann/EnterpriseArchitect_hoTools#12]
I use EA-15 x86 and EA16 x64, and would like to be able to use hoTools with both.

**Comment by Helmut-Ortmann** [comment]
Hello Tim,

The x64 version you find at:

- https://github.com/Helmut-Ortmann/EnterpriseArchitect_hoTools/releases/tag/V3.10

You have to install it independently of the X86(32-bit) release. I admit I should better support the x64 release.

I hope it will help you.

Best regards,

Helmut

**Comment by Helmut-Ortmann** [comment]
Released V4.0.0 with
- an improved collection of DLL-registration information with heat (in Build-event of ..Root,...Gui)
- bug fixing 
- update of used libraries
- About with output of dll type (x86/x64)
