### ISSUE TITLE
Find button disabled after find is performed on Find & Replace dialog

### ISSUE THREAD

**Issue by kubics** [Helmut-Ortmann/EnterpriseArchitect_hoTools#2]
Hi. Find & Replace works as expected for me, but I have to restart Enterprise Architect after every single Find, because when Find is performed, the "Find" button is disabled and it only can be enabled by restarting EA.

I have EA 13.0.1308 and HoTools 3.0.1

I do:
1. Open Find & Replace dialog from hoTools plugin.
2. Select field and item types
3. Enter Find string
4. Enter Replace string
(now Find is enabled and Show is disabled)
5. Click on Find 
(after search Find is disabled and Show is enabled)
6. Now I can open Show dialog and perform my replaces
7. After closing Show dialog I would like to perform another search, but Find button is still disabled to be able to Search and Replace again I have to restart EA

**Comment by Helmut-Ortmann** [comment]
Hi,

thanks for your feedback.

I corrected the error in release 3.0.2. There are some new buttons to boost
handling. One is 'Cancel' to start a new search/find.

Best regards,

Helmut

**Comment by Helmut-Ortmann** [comment]
Fixed in release 3.0.2 Additional Cancel button.

Rational: The buttons got somehow minimized.

**Comment by kubics** [comment]
Thanks. It works now.
