### ISSUE TITLE
Feature request: Find (and Replace) in structured specification

### ISSUE THREAD

**Issue by kubics** [Helmut-Ortmann/EnterpriseArchitect_hoTools#3]
Would it be possible to extend Find (or better Find & Replace) by searching also in "deeper" fields, e.g. Use Case scenarios? Thanks

**Comment by Helmut-Ortmann** [comment]
hoTools supports out of the box SQL searches and calling an EA Script for the found results. Details you find at https://github.com/Helmut-Ortmann/EnterpriseArchitect_hoTools/wiki/Scripts

The EA Script (VBScript, JavaScript, JScript) then can perform arbitrary changes of the found data.

Currently, I don't look into extending the Find & Replace features. There is too much possible.

Often the easiest way is to export the model or the package to *.xml. Find the thing to change, change it and import it again. 

Kind regards,

Helmut
